services:
  ollama:
    build:
      context: .
      dockerfile: .docker/Dockerfile.ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "ollama list | grep -q qwen2.5:1.5b || exit 1"]
      interval: 10s
      timeout: 100s
      retries: 200
      start_period: 30s

  jupyter:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: jupyter_notebook
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - OLLAMA_BASE_URL=http://ollama:11434/v1
      - OLLAMA_API=http://ollama:11434/api/chat
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''

volumes:
  ollama_data:

